version: "3.8"
services:
  app:
    image: cbunlong/laravel_order_cuisine:v1.0
    container_name: order_cuisine
    restart: always
    volumes:
      - ./docker-entrypoint.sh:/var/www/html/docker-entrypoint.sh
      - storage_volume:/var/www/html/storage    #Share storage folder
    depends_on:
      - postgres
    networks:
      - laravel_network
    entrypoint: ["/bin/sh", "/var/www/html/docker-entrypoint.sh"]
  postgres:
    image: postgres:latest
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: cuisine
    ports:
      - "5432:5432"
    volumes:
      - /etc/postgres/data:/var/lib/postgresql/data
    networks:
      - laravel_network
  nginx:
    image: nginx:latest
    container_name: nginx_server
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - storage_volume:/var/www/html/storage    #Share storage with Nginx
    depends_on:
      - app
    networks:
      - laravel_network
networks:
  laravel_network:
    driver: bridge
#Define the shared volume for storage
volumes:
  storage_volume:
